version: '3'

services:
  selenium:
    image: selenium/standalone-chrome-debug:3.7.1-beryllium
    ports:
     - "4444:4444"
     - "5901:5900"

  digital-eye-api:
    build:
      context: $PWD/../digital-eye-api/
    image: digital-eye-api/app:latest
    working_dir: /digital-eye-projects
    entrypoint: 'python /var/www/app/digital-eye-api-server.py'
    ports:
     - "5000:5000"  
    volumes:
      - $PWD/../projects:/digital-eye-projects

  se-interpreter-custom:
    build:
      context: ./
    image: se-interpreter-custom/app:latest
    volumes:
      - $PWD/../projects:/digital-eye-projects
    entrypoint: 'bash'      
    #entrypoint: 'node_modules/se-interpreter/interpreter.js se-test-sceneCheck.json --driver-host=selenium:4444 --browser-browserName=chrome'      
    depends_on:
      - selenium
      - digital-eye-api

# Bash Command to run $ node_modules/se-interpreter/interpreter.js simple-test.json --driver-host=selenium:4444 --browser-browserName=chrome
# Bash Command to run $ node_modules/se-interpreter/interpreter.js se-test-sceneCheck.json --driver-host=selenium:4444 --browser-browserName=chrome